# ==========================
# Application Info
# ==========================
spring.application.name=audit-service
server.port=8086

# ==========================
# PostgreSQL Datasource
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_service_db
spring.datasource.username=postgres
spring.datasource.password=Root12
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Kafka Consumer Config
# ==========================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=audit-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.enterprise.auditservice.kafka.AuditEventMessage

# Topics this service will consume (confirm exact names with the team)
audit.kafka.topics.role-events=role-events
audit.kafka.topics.permission-events=permission-events
audit.kafka.topics.security-events=security-events
audit.kafka.topics.user-events=user-events