# Optional local override.
# Change these values if your PostgreSQL setup is different.

spring.datasource.url=jdbc:postgresql://localhost:5432/oneenterprise_tenant_db
spring.datasource.username=postgres
spring.datasource.password=7675093749
